# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5603059f32ee237c574833fbc7122ac36b623f0d8316b1f735b59378c099d6aa0cddbc1fdc40c4aadfced6169b5921f2f5e6dcfb8249599ec51653ef671b097

test:
  secret_key_base: df54631d660a1c7d32402cf7d63d3989a84c355027d5880d8bccd698792557eff28dd2d946086c7d74303b9945f7c434d66bec94768e1239eb4a6891339f1a0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
