AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

# Comments don't need to be in English only
Style/AsciiComments:
  Enabled: false

# Do not enforce documentation rules
Style/Documentation:
  Enabled: false

# Default 80
Metrics/LineLength:
  Max: 120
